/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VecnehladnyPremisesWlList {
    }
}
declare global {
    interface HTMLVecnehladnyPremisesWlListElement extends Components.VecnehladnyPremisesWlList, HTMLStencilElement {
    }
    var HTMLVecnehladnyPremisesWlListElement: {
        prototype: HTMLVecnehladnyPremisesWlListElement;
        new (): HTMLVecnehladnyPremisesWlListElement;
    };
    interface HTMLElementTagNameMap {
        "vecnehladny-premises-wl-list": HTMLVecnehladnyPremisesWlListElement;
    }
}
declare namespace LocalJSX {
    interface VecnehladnyPremisesWlList {
    }
    interface IntrinsicElements {
        "vecnehladny-premises-wl-list": VecnehladnyPremisesWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vecnehladny-premises-wl-list": LocalJSX.VecnehladnyPremisesWlList & JSXBase.HTMLAttributes<HTMLVecnehladnyPremisesWlListElement>;
        }
    }
}
